project:
  type: book
execute:
  freeze: auto
book:
  title: "Computational Linear Algebra"
  code-links: binder
  author: "Siju Swamy"
  date: "7/16/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - module_1.qmd
    - module_2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
jupyter: python3



