project:
  type: book
execute:
  freeze: auto
book:
  favicon: CME_logo.JPG
  title: "Computational Linear Algebra"
  author: "Siju Swamy"
  date: "7/16/2024"
  search: true
  repo-url: https://github.com/sijuswamy/Computational-Linear-Algebra
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
 
  chapters:
    - index.qmd
    - intro.qmd
    - module_1.qmd
    - module_2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png
jupyter: python3
margin-header: |
  ![Computational Mathematics](CME_logo.JPG)


