project:
  type: book
execute:
  freeze: auto
book:
  favicon: CME_logo.JPG
  title: "Computational Linear Algebra"
  author: "Siju Swamy"
  date: "7/16/2024"
  search: true
  repo-url: https://github.com/sijuswamy/Computational-Linear-Algebra
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
 
  chapters:
    - index.qmd
    - intro.qmd
    - module_1.qmd
    - module_2.qmd
    - module_3.qmd
    - module_4.qmd
    - module_5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-overflow: wrap
    theme: cosmo
  pdf:
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }
    documentclass: scrreprt
    
  epub:
    cover-image: cover.png
jupyter: python3
margin-header: |
  ![Computational Mathematics](CME_logo.JPG)


